### ISSUE TITLE
cs4.4连接报错

### ISSUE THREAD

**Issue by Vipersec1** [TryHello/DogCs4.4#7]
用原版cs4.4服务端，连接不上，大佬
![image](https://user-images.githubusercontent.com/100136027/178133608-da6b2a0b-10f5-4496-a9a5-3a2bd3bad652.png)
![image](https://user-images.githubusercontent.com/100136027/178133633-2c97db00-1da5-410c-bdfa-5022fb104c7f.png)

**Comment by TryHello** [comment]
我服，都给你改好了，为什么还要用原版，这种问题就别问了好吗。不是readme里都说了，都是改的，肯定也要用我这个起服务端啊。。。、
